services:
  frontend:
    container_name: controler_frontend
    build:
      context: ./message-broker-frontend
      dockerfile: Dockerfile
      args:
        FIREBASE_API_KEY: ${FIREBASE_API_KEY}
        FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
        FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
        FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
        FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
        FIREBASE_APP_ID: ${FIREBASE_APP_ID}
    image: queue-service-controller:v1
    environment:
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
    networks:
      - internalnet
  ibmmq:
    image: ibmcom/mq:latest
    container_name: ibm-mq
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: ${MY_MQ_QMGR}  # Queue manager name
      MQ_APP_PASSWORD: ${MY_MQ_PASSWORD}  # Password for 'admin' user
    ports:
      - "1414:1414"  # MQ communication port
      - "9443:9443"  # MQ Web Console/REST API port
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge